### ISSUE TITLE
Wheres is "rates" lib?

### ISSUE THREAD

**Issue by TadeoDGAguilar** [aidanwmw/iPyBBN#1]
Hi,

I try to compile your notebook, but the only issue that I have

What is the lib rates? Where is that?

Regards!

**Comment by aidanwmw** [comment]
My apologies for not resolving this. This was meant to be a private repo to store my code and I will archive it soon. However, I have finished a version of this code at [this public repository(https://github.com/aidanwmw/BBN-simple)] that has a Jupyter book and an arXiv paper, if you are still interested in the physics. 

If you're interested in doing this yourself, rates can be found from the nuclear ReacLib library, which is fairly up-to-date, assuming you do not need highly accurate stellar rates.
